<?php
declare(strict_types=1);

$config = require __DIR__ . '/../config/config.php';

require_once __DIR__ . '/../src/Db.php';
require_once __DIR__ . '/../src/Auth.php';

Auth::requireLogin();

// --- Helper functions --------------------------------------------------------

function get_setting(PDO $pdo, string $key): ?string
{
    $stmt = $pdo->prepare('SELECT setting_value FROM sync_settings WHERE setting_key = :key ORDER BY id DESC LIMIT 1');
    $stmt->execute([':key' => $key]);
    $row = $stmt->fetch(PDO::FETCH_ASSOC);
    if ($row && isset($row['setting_value'])) {
        return (string)$row['setting_value'];
    }
    return null;
}

function set_setting(PDO $pdo, string $key, string $value): void
{
    // Ensure only one row per setting_key
    $stmt = $pdo->prepare('DELETE FROM sync_settings WHERE setting_key = :key');
    $stmt->execute([':key' => $key]);

    $stmt = $pdo->prepare('INSERT INTO sync_settings (setting_key, setting_value) VALUES (:key, :value)');
    $stmt->execute([
        ':key'   => $key,
        ':value' => $value,
    ]);
}

function format_display_time(?string $value, DateTimeZone $tz): ?string
{
    if ($value === null || $value === '') {
        return null;
    }

    try {
        $dt = new DateTimeImmutable($value);
        return $dt->setTimezone($tz)->format('Y-m-d h:i A T');
    } catch (Throwable $e) {
        return $value;
    }
}

/**
 * Load key=value pairs from config/.env (simple parser).
 */
function load_env_pairs(string $path): array
{
    if (!file_exists($path)) {
        return [];
    }
    $lines = @file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
    $out = [];
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || str_starts_with($line, '#')) {
            continue;
        }
        [$k, $v] = array_pad(explode('=', $line, 2), 2, '');
        $k = trim($k);
        $v = trim($v, " \t\n\r\0\x0B\"'");
        if ($k !== '') {
            $out[$k] = $v;
        }
    }
    return $out;
}

/**
 * Write key=value pairs to config/.env. Comments are not preserved.
 */
function save_env_pairs(string $path, array $data): void
{
    $lines = ["# Generated by settings on " . date('c')];
    foreach ($data as $k => $v) {
        $lines[] = $k . '=' . $v;
    }
    $content = implode(PHP_EOL, $lines) . PHP_EOL;
    if (file_put_contents($path, $content, LOCK_EX) === false) {
        throw new RuntimeException('Unable to write to ' . $path);
    }
}

// --- Bootstrap DB ------------------------------------------------------------

try {
    $db  = Db::getInstance($config['db']);
    $pdo = $db->getConnection();
} catch (Throwable $e) {
    http_response_code(500);
    echo '<h1>Database error</h1>';
    echo '<pre>' . htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8') . '</pre>';
    exit;
}

$message = null;
$error   = null;
$envPath = __DIR__ . '/../config/.env';
$envPairs = load_env_pairs($envPath);

// --- Handle form submission --------------------------------------------------

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        if (!file_exists($envPath)) {
            throw new RuntimeException('config/.env not found; please run setup or create it before saving SMTP settings.');
        }
        $action = $_POST['action'] ?? 'save';
        // Notifications
        $notificationEmail = isset($_POST['notification_email'])
            ? trim((string)$_POST['notification_email'])
            : '';
        if ($notificationEmail !== '') {
            set_setting($pdo, 'notification_email', $notificationEmail);
        } else {
            // allow blank to "turn off" notifications
            set_setting($pdo, 'notification_email', '');
        }

        // Stripe payout sync (online / Stripe donations)
        $depositBankName = trim((string)($_POST['deposit_bank_account_name'] ?? ''));
        $incomeName      = trim((string)($_POST['income_account_name'] ?? ''));
        $refundName      = trim((string)($_POST['stripe_refund_account_name'] ?? ''));
        $feeName         = trim((string)($_POST['stripe_fee_account_name'] ?? ''));

        if ($depositBankName !== '') {
            set_setting($pdo, 'deposit_bank_account_name', $depositBankName);
        }
        if ($incomeName !== '') {
            set_setting($pdo, 'income_account_name', $incomeName);
        }
        if ($refundName !== '') {
            set_setting($pdo, 'stripe_refund_account_name', $refundName);
        }
        if ($feeName !== '') {
            set_setting($pdo, 'stripe_fee_account_name', $feeName);
        }

        // Batch sync (committed PCO batches)
        $enableBatchSync = isset($_POST['enable_batch_sync']) ? '1' : '0';
        set_setting($pdo, 'enable_batch_sync', $enableBatchSync);

        $batchBankName   = trim((string)($_POST['batch_deposit_bank_account_name'] ?? ''));
        $batchIncomeName = trim((string)($_POST['batch_income_account_name'] ?? ''));

        if ($batchBankName !== '') {
            set_setting($pdo, 'batch_deposit_bank_account_name', $batchBankName);
        }
        if ($batchIncomeName !== '') {
            set_setting($pdo, 'batch_income_account_name', $batchIncomeName);
        }

        // Registrations sync
        $regDepositName  = trim((string)($_POST['reg_deposit_bank_account_name'] ?? ''));
        $regIncomeName   = trim((string)($_POST['reg_income_account_name'] ?? ''));
        $regClassName    = trim((string)($_POST['reg_class_name'] ?? ''));
        $regLocationName = trim((string)($_POST['reg_location_name'] ?? ''));

        if ($regDepositName !== '') {
            set_setting($pdo, 'reg_deposit_bank_account_name', $regDepositName);
        }
        if ($regIncomeName !== '') {
            set_setting($pdo, 'reg_income_account_name', $regIncomeName);
        }
        set_setting($pdo, 'reg_class_name', $regClassName);
        set_setting($pdo, 'reg_location_name', $regLocationName);

        // Display timezone
        $tzInput = trim((string)($_POST['display_timezone'] ?? ''));
        if ($tzInput === '') {
            $tzInput = 'UTC';
        }
        try {
            $tzObj = new DateTimeZone($tzInput);
            set_setting($pdo, 'display_timezone', $tzObj->getName());
            $displayTimezone    = $tzObj->getName();
            $displayTimezoneObj = $tzObj;
        } catch (Throwable $e) {
            // leave existing on error
        }

        // SMTP / mail-from (.env)
        $mailFrom    = trim((string)($_POST['MAIL_FROM'] ?? ''));
        $smtpHost    = trim((string)($_POST['MAIL_SMTP_HOST'] ?? ''));
        $smtpPort    = (int)($_POST['MAIL_SMTP_PORT'] ?? 587);
        if ($smtpPort <= 0) { $smtpPort = 587; }
        $smtpEnc     = strtolower(trim((string)($_POST['MAIL_SMTP_ENCRYPTION'] ?? 'tls')));
        if ($smtpEnc === '') { $smtpEnc = 'tls'; }
        $smtpUser    = trim((string)($_POST['MAIL_SMTP_USER'] ?? ''));
        $smtpPass    = trim((string)($_POST['MAIL_SMTP_PASS'] ?? ''));

        $envPairs['MAIL_FROM']            = $mailFrom;
        $envPairs['MAIL_SMTP_HOST']       = $smtpHost;
        $envPairs['MAIL_SMTP_PORT']       = (string)$smtpPort;
        $envPairs['MAIL_SMTP_ENCRYPTION'] = $smtpEnc;
        $envPairs['MAIL_SMTP_USER']       = $smtpUser;
        $envPairs['MAIL_SMTP_PASS']       = $smtpPass;

        save_env_pairs($envPath, $envPairs);

        if ($action === 'save_and_test_mail') {
            require_once __DIR__ . '/../src/Mailer.php';
            $mailer = new Mailer($mailFrom, [
                'smtp_host'       => $smtpHost,
                'smtp_port'       => $smtpPort,
                'smtp_user'       => $smtpUser,
                'smtp_pass'       => $smtpPass,
                'smtp_encryption' => $smtpEnc,
            ]);
            $target = $notificationEmail ?: ($mailFrom ?: $smtpUser);
            if (!$target) {
                throw new RuntimeException('No notification email or from address available to send test.');
            }
            $mailer->send($target, 'SMTP test from qbo-pco-sync', "Test email sent at " . date('c') . "\nMode: " . ($smtpHost !== '' ? 'SMTP' : 'mail()'));
            $message = 'Settings saved and test email sent to ' . htmlspecialchars($target, ENT_QUOTES, 'UTF-8') . '.';
        } else {
            $message = 'Settings saved successfully.';
        }
    } catch (Throwable $e) {
        $error = 'Error saving settings: ' . $e->getMessage();
    }
}

// --- Load current values -----------------------------------------------------

$notificationEmail = get_setting($pdo, 'notification_email') ?? '';

// Stripe payout sync settings
$depositBankName = get_setting($pdo, 'deposit_bank_account_name')
    ?? 'TRINITY 2000 CHECKING';

$incomeAccountName = get_setting($pdo, 'income_account_name')
    ?? 'OPERATING INCOME:WEEKLY OFFERINGS:PLEDGES';

$stripeRefundAccountName = get_setting($pdo, 'stripe_refund_account_name') ?? '';

$stripeFeeAccountName = get_setting($pdo, 'stripe_fee_account_name')
    ?? 'OPERATING EXPENSES:MINISTRY EXPENSES:PROCESSING FEES';

// Batch sync settings (now also in sync_settings)
$enableBatchSync = (get_setting($pdo, 'enable_batch_sync') === '1');

$batchDepositBankName = get_setting($pdo, 'batch_deposit_bank_account_name')
    ?? $depositBankName;

$batchIncomeAccountName = get_setting($pdo, 'batch_income_account_name')
    ?? $incomeAccountName;

// Registrations settings
$regDepositBankName = get_setting($pdo, 'reg_deposit_bank_account_name')
    ?? $depositBankName;
$regIncomeAccountName = get_setting($pdo, 'reg_income_account_name')
    ?? $incomeAccountName;
$regClassName = get_setting($pdo, 'reg_class_name') ?? '';
$regLocationName = get_setting($pdo, 'reg_location_name') ?? '';

// Display timezone
$displayTimezone = get_setting($pdo, 'display_timezone') ?? 'UTC';
try {
    $displayTimezoneObj = new DateTimeZone($displayTimezone);
} catch (Throwable $e) {
    $displayTimezone     = 'UTC';
    $displayTimezoneObj  = new DateTimeZone('UTC');
}

$mailFrom       = $envPairs['MAIL_FROM'] ?? (getenv('MAIL_FROM') ?: '');
$mailSmtpHost   = $envPairs['MAIL_SMTP_HOST'] ?? (getenv('MAIL_SMTP_HOST') ?: '');
$mailSmtpPort   = $envPairs['MAIL_SMTP_PORT'] ?? (getenv('MAIL_SMTP_PORT') ?: '587');
$mailSmtpEnc    = $envPairs['MAIL_SMTP_ENCRYPTION'] ?? (getenv('MAIL_SMTP_ENCRYPTION') ?: 'tls');
$mailSmtpUser   = $envPairs['MAIL_SMTP_USER'] ?? (getenv('MAIL_SMTP_USER') ?: '');
$mailSmtpPass   = $envPairs['MAIL_SMTP_PASS'] ?? (getenv('MAIL_SMTP_PASS') ?: '');

// Last sync windows (read-only info)
$lastStripeCompletedAt = get_setting($pdo, 'last_completed_at');
$lastBatchCompletedAt  = get_setting($pdo, 'last_batch_sync_completed_at');
$lastStripeDisplay     = format_display_time($lastStripeCompletedAt, $displayTimezoneObj);
$lastBatchDisplay      = format_display_time($lastBatchCompletedAt, $displayTimezoneObj);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Settings - PCO &harr; QBO Sync</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@500;700&display=swap');
        :root {
            --bg: #0b1224;
            --panel: rgba(15, 25, 46, 0.78);
            --card: rgba(22, 32, 55, 0.9);
            --border: rgba(255, 255, 255, 0.08);
            --text: #e9eef7;
            --muted: #9daccc;
            --accent: #2ea8ff;
            --accent-strong: #0d7adf;
            --success: #39d98a;
            --warn: #f2c94c;
            --error: #ff7a7a;
        }
        body {
            font-family: 'Manrope', 'Segoe UI', sans-serif;
            margin: 0;
            background: radial-gradient(circle at 15% 20%, rgba(46, 168, 255, 0.12), transparent 25%),
                        radial-gradient(circle at 85% 10%, rgba(57, 217, 138, 0.15), transparent 22%),
                        radial-gradient(circle at 70% 70%, rgba(242, 201, 76, 0.08), transparent 30%),
                        var(--bg);
            color: var(--text);
            min-height: 100vh;
        }
        * { box-sizing: border-box; }
        .page {
            max-width: 1050px;
            margin: 0 auto;
            padding: 2.4rem 1.25rem 3rem;
        }
        .hero {
            background: var(--panel);
            border: 1px solid var(--border);
            border-radius: 18px;
            padding: 1.4rem 1.5rem;
            box-shadow: 0 10px 40px rgba(0,0,0,0.25);
            position: relative;
            overflow: hidden;
            display: flex;
            align-items: flex-start;
            justify-content: space-between;
            gap: 1rem;
            flex-wrap: wrap;
        }
        .hero::after {
            content: '';
            position: absolute;
            inset: 0;
            background: radial-gradient(circle at 30% 40%, rgba(46,168,255,0.15), transparent 35%),
                        radial-gradient(circle at 80% 10%, rgba(57,217,138,0.12), transparent 35%);
            pointer-events: none;
        }
        .hero > * { position: relative; z-index: 1; }
        .eyebrow {
            letter-spacing: 0.05em;
            text-transform: uppercase;
            color: var(--muted);
            font-size: 0.8rem;
            margin-bottom: 0.25rem;
        }
        h1 {
            margin: 0 0 0.35rem;
            font-size: 2rem;
            letter-spacing: -0.01em;
        }
        .lede {
            color: var(--muted);
            margin: 0;
            max-width: 58ch;
            line-height: 1.6;
        }
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            gap: 0.5rem;
            padding: 0.65rem 1rem;
            background: linear-gradient(135deg, var(--accent), var(--accent-strong));
            color: #0b1324;
            font-weight: 700;
            text-decoration: none;
            border-radius: 10px;
            border: 1px solid rgba(255,255,255,0.08);
            box-shadow: 0 10px 25px rgba(13,122,223,0.35);
            transition: transform 120ms ease, box-shadow 120ms ease, background 150ms ease;
        }
        .btn:hover {
            transform: translateY(-1px);
            box-shadow: 0 14px 30px rgba(13,122,223,0.4);
        }
        .btn.secondary {
            background: transparent;
            color: var(--text);
            border: 1px solid var(--border);
            box-shadow: none;
        }
        .flash {
            margin-top: 1rem;
            padding: 0.85rem 1rem;
            border-radius: 10px;
            border: 1px solid var(--border);
            display: grid;
            grid-template-columns: auto 1fr;
            gap: 0.75rem;
            align-items: center;
        }
        .flash.success {
            background: rgba(57, 217, 138, 0.12);
            border-color: rgba(57, 217, 138, 0.35);
        }
        .flash.error {
            background: rgba(255, 122, 122, 0.12);
            border-color: rgba(255, 122, 122, 0.35);
        }
        .flash .tag {
            background: rgba(255, 255, 255, 0.06);
            padding: 0.35rem 0.65rem;
            border-radius: 999px;
            font-size: 0.85rem;
            border: 1px solid var(--border);
        }
        .form-stack {
            margin-top: 1.5rem;
            display: grid;
            gap: 1rem;
        }
        .card {
            background: var(--card);
            border: 1px solid var(--border);
            border-radius: 14px;
            padding: 1.2rem 1.25rem;
            box-shadow: 0 8px 30px rgba(0,0,0,0.18);
        }
        .section-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 1rem;
            flex-wrap: wrap;
            margin-bottom: 0.85rem;
        }
        .section-title {
            margin: 0;
            font-size: 1.1rem;
            letter-spacing: -0.01em;
        }
        .section-sub {
            margin: 0;
            color: var(--muted);
            font-size: 0.95rem;
        }
        .field {
            display: grid;
            gap: 0.3rem;
            margin-bottom: 0.85rem;
        }
        .field label {
            font-weight: 700;
            letter-spacing: -0.01em;
        }
        .field input[type="text"],
        .field input[type="email"],
        .field input[type="number"],
        .field input[type="password"],
        .field input[type="url"] {
            width: 100%;
            max-width: 520px;
            padding: 0.65rem 0.75rem;
            border-radius: 10px;
            border: 1px solid rgba(255,255,255,0.14);
            background: rgba(255,255,255,0.04);
            color: var(--text);
            font-size: 1rem;
        }
        .field input:focus {
            outline: 2px solid rgba(46,168,255,0.4);
            border-color: rgba(46,168,255,0.45);
        }
        .hint {
            font-size: 0.9rem;
            color: var(--muted);
            line-height: 1.45;
        }
        .checkbox-row {
            display: grid;
            gap: 0.35rem;
            margin-bottom: 0.7rem;
        }
        .checkbox-row label {
            font-weight: 700;
            display: inline-flex;
            align-items: center;
            gap: 0.45rem;
            letter-spacing: -0.01em;
        }
        .readonly-values {
            display: grid;
            gap: 0.4rem;
            font-size: 0.95rem;
            color: var(--text);
        }
        .readonly-values code {
            font-size: 0.9rem;
            color: #d7e8ff;
        }
        .select {
            width: 100%;
            max-width: 320px;
            padding: 0.65rem 0.75rem;
            border-radius: 10px;
            border: 1px solid rgba(255,255,255,0.14);
            background: rgba(255,255,255,0.04);
            color: #0d7adf;
            font-size: 1rem;
        }
        .select:focus {
            outline: 2px solid rgba(46,168,255,0.4);
            border-color: rgba(46,168,255,0.45);
        }
        .actions {
            display: flex;
            justify-content: flex-end;
        }
        button[type="submit"] {
            border: none;
            cursor: pointer;
            font-size: 1rem;
        }
        .footer {
            margin-top: 1.4rem;
            text-align: center;
            color: var(--muted);
            font-size: 0.9rem;
        }
        .footer a { color: var(--accent); text-decoration: none; }
        .footer a:hover { color: #dff1ff; }
        @media (max-width: 720px) {
            .hero { padding: 1.2rem 1.1rem; }
            .section-header { align-items: flex-start; }
            .btn.secondary { width: 100%; justify-content: center; }
            .actions { justify-content: stretch; }
            .actions .btn { width: 100%; }
        }
    </style>
</head>
<body>
<div class="page">
    <div class="hero">
        <div>
            <div class="eyebrow">Configuration</div>
            <h1>Settings</h1>
            <p class="lede">Tune notifications and QuickBooks targets so syncs land exactly where you want them.</p>
        </div>
        <a class="btn secondary" href="index.php">&larr; Back to dashboard</a>
    </div>

    <?php if ($message): ?>
        <div class="flash success">
            <span class="tag">Saved</span>
            <div><?php echo htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?></div>
        </div>
    <?php endif; ?>

    <?php if ($error): ?>
        <div class="flash error">
            <span class="tag">Issue</span>
            <div><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></div>
        </div>
    <?php endif; ?>

    <form method="post" class="form-stack">
        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Notifications</p>
                    <p class="section-title">Alert routing</p>
                    <p class="section-sub">Where to send sync errors or partial successes.</p>
                </div>
            </div>
            <div class="field">
                <label for="notification_email">Error / warning notification email</label>
                <input
                    type="email"
                    id="notification_email"
                    name="notification_email"
                    value="<?php echo htmlspecialchars($notificationEmail, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    If set, the app will send an email when a Stripe or batch sync finishes with errors or partial success.
                    Leave blank to disable email notifications.
                </div>
            </div>
        </div>

        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Email</p>
                    <p class="section-title">From address & SMTP</p>
                    <p class="section-sub">Configure outbound email for notifications. SMTP is recommended.</p>
                </div>
            </div>
            <div class="grid">
                <div class="field">
                    <label for="MAIL_FROM">Mail from</label>
                    <input
                        type="email"
                        id="MAIL_FROM"
                        name="MAIL_FROM"
                        value="<?php echo htmlspecialchars($mailFrom, ENT_QUOTES, 'UTF-8'); ?>"
                        required
                    >
                    <div class="hint">Default from/reply-to used for notification emails.</div>
                </div>
                <div class="field">
                    <label for="MAIL_SMTP_HOST">SMTP host</label>
                    <input
                        type="text"
                        id="MAIL_SMTP_HOST"
                        name="MAIL_SMTP_HOST"
                        value="<?php echo htmlspecialchars($mailSmtpHost, ENT_QUOTES, 'UTF-8'); ?>"
                        placeholder="smtp.dreamhost.com"
                    >
                </div>
                <div class="field">
                    <label for="MAIL_SMTP_PORT">SMTP port</label>
                    <input
                        type="number"
                        id="MAIL_SMTP_PORT"
                        name="MAIL_SMTP_PORT"
                        value="<?php echo htmlspecialchars((string)$mailSmtpPort, ENT_QUOTES, 'UTF-8'); ?>"
                        placeholder="587"
                    >
                </div>
                <div class="field">
                    <label for="MAIL_SMTP_ENCRYPTION">Encryption (tls/ssl)</label>
                    <input
                        type="text"
                        id="MAIL_SMTP_ENCRYPTION"
                        name="MAIL_SMTP_ENCRYPTION"
                        value="<?php echo htmlspecialchars($mailSmtpEnc, ENT_QUOTES, 'UTF-8'); ?>"
                        placeholder="tls"
                    >
                </div>
                <div class="field">
                    <label for="MAIL_SMTP_USER">SMTP username</label>
                    <input
                        type="text"
                        id="MAIL_SMTP_USER"
                        name="MAIL_SMTP_USER"
                        value="<?php echo htmlspecialchars($mailSmtpUser, ENT_QUOTES, 'UTF-8'); ?>"
                        placeholder="you@your-domain.com"
                    >
                </div>
                <div class="field">
                    <label for="MAIL_SMTP_PASS">SMTP password</label>
                    <input
                        type="password"
                        id="MAIL_SMTP_PASS"
                        name="MAIL_SMTP_PASS"
                        value="<?php echo htmlspecialchars($mailSmtpPass, ENT_QUOTES, 'UTF-8'); ?>"
                    >
                </div>
            </div>
            <div class="hint">
                Leave host blank to fall back to PHP <code>mail()</code> (less reliable). For DreamHost use host <code>smtp.dreamhost.com</code>,
                port <code>587</code>, encryption <code>tls</code>, and your mailbox username/password.
            </div>
            <div class="field" style="margin-top:0.6rem;">
                <button type="submit" name="action" value="save_and_test_mail" class="btn secondary">Save and send test email</button>
                <div class="hint">Saves settings above, then sends a test to the notification email.</div>
            </div>
        </div>

        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Stripe payout sync</p>
                    <p class="section-title">Online donations</p>
                    <p class="section-sub">Control where Stripe payout deposits and fee lines are booked.</p>
                </div>
            </div>
            <div class="field">
                <label for="deposit_bank_account_name">Deposit bank account (QBO name)</label>
                <input
                    type="text"
                    id="deposit_bank_account_name"
                    name="deposit_bank_account_name"
                    value="<?php echo htmlspecialchars($depositBankName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    This should match the name of the bank account in QuickBooks that receives Stripe deposits
                    (for example: <code>TRINITY 2000 CHECKING</code>).
                </div>
            </div>

            <div class="field">
                <label for="income_account_name">Income account (QBO name)</label>
                <input
                    type="text"
                    id="income_account_name"
                    name="income_account_name"
                    value="<?php echo htmlspecialchars($incomeAccountName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    Used for gross donation lines (for example: <code>OPERATING INCOME:WEEKLY OFFERINGS:PLEDGES</code>).
                    Use <a href="fund-mapping.php">Fund mapping</a> to override this per fund.
                </div>
            </div>

            <div class="field">
                <label for="stripe_refund_account_name">Refund income account (QBO name)</label>
                <input
                    type="text"
                    id="stripe_refund_account_name"
                    name="stripe_refund_account_name"
                    value="<?php echo htmlspecialchars($stripeRefundAccountName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    If blank, refunds will post back to the main income account.
                </div>
            </div>

            <div class="field">
                <label for="stripe_fee_account_name">Stripe fee expense account (QBO name)</label>
                <input
                    type="text"
                    id="stripe_fee_account_name"
                    name="stripe_fee_account_name"
                    value="<?php echo htmlspecialchars($stripeFeeAccountName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    Used for the negative fee lines (for example: <code>OPERATING EXPENSES:MINISTRY EXPENSES:PROCESSING FEES</code>).
                </div>
            </div>
        </div>

        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Batch sync</p>
                    <p class="section-title">Committed PCO Giving batches</p>
                    <p class="section-sub">Enable and route deposits created from committed batches.</p>
                </div>
            </div>

            <div class="checkbox-row">
                <label>
                    <input
                        type="checkbox"
                        name="enable_batch_sync"
                        value="1"
                        <?php echo $enableBatchSync ? 'checked' : ''; ?>
                    >
                    Enable sync of committed PCO Giving batches to QuickBooks
                </label>
                <div class="hint">
                    When enabled, the batch sync will create deposits in QBO for committed batches, grouping by fund and applying
                    the correct QBO Class and Location based on your fund mapping.
                </div>
            </div>

            <div class="field">
                <label for="batch_deposit_bank_account_name">Batch deposit bank account (QBO name)</label>
                <input
                    type="text"
                    id="batch_deposit_bank_account_name"
                    name="batch_deposit_bank_account_name"
                    value="<?php echo htmlspecialchars($batchDepositBankName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    Bank account used for deposits created from committed batches. Defaults to the Stripe deposit account if left the same.
                </div>
            </div>

            <div class="field">
                <label for="batch_income_account_name">Batch income account (QBO name)</label>
                <input
                    type="text"
                    id="batch_income_account_name"
                    name="batch_income_account_name"
                    value="<?php echo htmlspecialchars($batchIncomeAccountName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">
                    Income account used for gross donation lines from committed batches. Defaults to the Stripe income account if left the same.
                </div>
            </div>
        </div>

        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Registrations sync</p>
                    <p class="section-title">Event payments (Registrations)</p>
                    <p class="section-sub">Default QBO targets for PCO Registrations payments.</p>
                </div>
            </div>

            <div class="field">
                <label for="reg_deposit_bank_account_name">Registrations deposit bank account (QBO name)</label>
                <input
                    type="text"
                    id="reg_deposit_bank_account_name"
                    name="reg_deposit_bank_account_name"
                    value="<?php echo htmlspecialchars($regDepositBankName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">Bank account used for deposits created from Registrations payments.</div>
            </div>

            <div class="field">
                <label for="reg_income_account_name">Registrations income account (QBO name)</label>
                <input
                    type="text"
                    id="reg_income_account_name"
                    name="reg_income_account_name"
                    value="<?php echo htmlspecialchars($regIncomeAccountName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">Income account for gross registration payments.</div>
            </div>

            <div class="field">
                <label for="reg_class_name">Registrations Class (QBO name, optional)</label>
                <input
                    type="text"
                    id="reg_class_name"
                    name="reg_class_name"
                    value="<?php echo htmlspecialchars($regClassName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">Optional Class to apply to registrations lines.</div>
            </div>

            <div class="field">
                <label for="reg_location_name">Registrations Location (QBO Department name, optional)</label>
                <input
                    type="text"
                    id="reg_location_name"
                    name="reg_location_name"
                    value="<?php echo htmlspecialchars($regLocationName, ENT_QUOTES, 'UTF-8'); ?>"
                >
                <div class="hint">Optional Location/Department to apply to registrations deposits.</div>
            </div>

            <div class="hint">Stripe fees for registrations will use the existing Stripe fee expense account.</div>
        </div>

        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Display</p>
                    <p class="section-title">Timezone</p>
                    <p class="section-sub">Used for showing dates/times on dashboard and previews.</p>
                </div>
            </div>
            <div class="field">
                <label for="display_timezone">Display timezone</label>
                <select id="display_timezone" name="display_timezone" class="select">
                    <?php
                    $tzList = DateTimeZone::listIdentifiers();
                    foreach ($tzList as $tz) {
                        $sel = ($tz === $displayTimezone) ? 'selected' : '';
                        echo '<option value="' . htmlspecialchars($tz, ENT_QUOTES, 'UTF-8') . "\" {$sel}>" . htmlspecialchars($tz, ENT_QUOTES, 'UTF-8') . '</option>';
                    }
                    ?>
                </select>
                <div class="hint">Times will be shown in this timezone in 12-hour format.</div>
            </div>
        </div>

        <div class="card">
            <div class="section-header">
                <div>
                    <p class="eyebrow" style="margin-bottom: 0.35rem;">Sync windows</p>
                    <p class="section-title">Read-only</p>
                    <p class="section-sub">Reference for the most recent sync windows.</p>
                </div>
            </div>
            <div class="readonly-values">
                <div>
                    <strong>Last Stripe payout sync window end (<?= htmlspecialchars($displayTimezoneObj->getName(), ENT_QUOTES, 'UTF-8') ?>):</strong>
                    <?php echo $lastStripeDisplay
                        ? htmlspecialchars($lastStripeDisplay, ENT_QUOTES, 'UTF-8')
                        : '<em>Not set yet</em>'; ?>
                </div>
                <div>
                    <strong>Last batch sync window end (<?= htmlspecialchars($displayTimezoneObj->getName(), ENT_QUOTES, 'UTF-8') ?>):</strong>
                    <?php echo $lastBatchDisplay
                        ? htmlspecialchars($lastBatchDisplay, ENT_QUOTES, 'UTF-8')
                        : '<em>Not set yet</em>'; ?>
                </div>
                <div class="hint">
                    These timestamps are advanced automatically each time the sync runs. If you ever need to reset them manually,
                    you can do so via your database (in the <code>sync_settings</code> table).
                </div>
            </div>
        </div>

        <div class="actions">
            <button type="submit" class="btn">Save settings</button>
        </div>
    </form>
    <div class="footer">
        &copy; <?= date('Y') ?> Rev. Tommy Sheppard <a href="help.php">Help</a>
    </div>
</div>
</body>
</html>
